version: "3.1"

services:
  db:
    container_name: postgres
    image: postgres:11.2
    restart: always
    env_file:
      - docker.env
    volumes:
      - ../db:/var/lib/postgresqldata/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
